[package]
name = "iPhotoSync"
version = "0.1.0"
authors = ["Mikhail Lappo <miklelappo@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0" }
indicatif = { version = "0.14.0" }
rusqlite = { version = "0.21.0" }
